//
//  CloudLogicAPIListViewController.m
//  MySampleApp
//
//
// Copyright 2017 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
//
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to 
// copy, distribute and modify it.
//
// Source code generated from template: aws-my-sample-app-ios-objc v0.15
//

#import "CloudLogicAPIListViewController.h"
#import "CloudLogicAPI.h"
#import "CloudLogicAPIFactory.h"
#import "CloudLogicAPIOperationsViewController.h"

@interface CloudLogicAPIListViewController ()

@property (nonatomic, strong) NSArray<CloudLogicAPI *> *cloudLogicAPIs;

@end

@interface CloudLogicAPIOperationsViewController ()

@property (nonatomic, strong) CloudLogicAPI *cloudLogicAPI;
@property (nonatomic, strong) NSString *apiPathValue;

@end

@implementation CloudLogicAPIListViewController

- (void)viewDidLoad {
    [super viewDidLoad];
    
    self.navigationItem.backBarButtonItem = [[UIBarButtonItem alloc] initWithTitle:@"Back"
                                                                             style:UIBarButtonItemStylePlain
                                                                            target:nil
                                                                            action:nil];
    self.cloudLogicAPIs = [CloudLogicAPIFactory supportedCloudLogicAPIs];
}

#pragma mark - Table view data source

- (NSInteger)numberOfSectionsInTableView:(UITableView *)tableView {
    return [self.cloudLogicAPIs count];
}

- (NSInteger)tableView:(UITableView *)tableView numberOfRowsInSection:(NSInteger)section {
    return 1;
}

- (UITableViewCell *)tableView:(UITableView *)tableView cellForRowAtIndexPath:(NSIndexPath *)indexPath {
    CloudLogicAPITableCell *cell = [tableView dequeueReusableCellWithIdentifier:@"CloudLogicAPITableCell" forIndexPath:indexPath];
    
    CloudLogicAPI *cloudLogicAPI = self.cloudLogicAPIs[indexPath.section];
    cell.cloudLogicAPIName.text = cloudLogicAPI.displayName;
    cell.cloudLogicAPIDescription.text = @"";
    if (cloudLogicAPI.apiDescription) {
        cell.cloudLogicAPIDescription.text = cloudLogicAPI.apiDescription;
    }
    return cell;
}

- (void)tableView:(UITableView *)tableView didSelectRowAtIndexPath:(NSIndexPath *)indexPath {
    [tableView deselectRowAtIndexPath:indexPath animated:YES];
    
    static NSString *showQueryResultSeque = @"CloudLogicAPIShowDetailsSegue";
    [self performSegueWithIdentifier:showQueryResultSeque sender:self.cloudLogicAPIs[indexPath.section]];
}

#pragma mark - Navigation

- (void)prepareForSegue:(UIStoryboardSegue *)segue sender:(id)sender {
    if ([segue.destinationViewController isKindOfClass:[CloudLogicAPIOperationsViewController class]]) {
        CloudLogicAPIOperationsViewController *destinationViewController = segue.destinationViewController;
        destinationViewController.cloudLogicAPI = sender;
    }
}

@end

@implementation CloudLogicAPITableCell

@end
