//
//  CloudLogicAPIPathSelectorViewController.h
//  MySampleApp
//
//
// Copyright 2017 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
//
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to 
// copy, distribute and modify it.
//
// Source code generated from template: aws-my-sample-app-ios-objc v0.15
//

#import <UIKit/UIKit.h>

@interface CloudLogicAPIPathSelectorViewController : UITableViewController

@property (weak, nonatomic) IBOutlet UITextField *searchText;

@end

@interface PathTableCell : UITableViewCell

@property (weak, nonatomic) IBOutlet UILabel *path;

@end

@protocol CloudLogicAPIPathSelectorModalVCDelegate <NSObject>

- (void)setSelectedValue:(NSString *)value;

@property (nonatomic,weak) id <CloudLogicAPIPathSelectorModalVCDelegate> delegate;

@end
