//
//  CloudLogicAPIOperationsViewController.h
//  MySampleApp
//
//
// Copyright 2017 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
//
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to 
// copy, distribute and modify it.
//
// Source code generated from template: aws-my-sample-app-ios-objc v0.15
//

#import <UIKit/UIKit.h>

@interface CloudLogicAPIOperationsViewController : UITableViewController

@property (weak, nonatomic) IBOutlet UILabel *apiEndpoint;
@property (weak, nonatomic) IBOutlet UITextField *apiPath;
@property (weak, nonatomic) IBOutlet UILabel *getPathLabel;
@property (weak, nonatomic) IBOutlet UILabel *putPathLabel;
@property (weak, nonatomic) IBOutlet UILabel *postPathLabel;
@property (weak, nonatomic) IBOutlet UILabel *deletePathLabel;
@property (weak, nonatomic) IBOutlet UILabel *patchPathLabel;
@property (weak, nonatomic) IBOutlet UILabel *headPathLabel;
@property (weak, nonatomic) IBOutlet UILabel *optionPathLabel;

@end
