//
//  CloudLogicAPIPathSelectorViewController.m
//  MySampleApp
//
//
// Copyright 2017 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
//
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to 
// copy, distribute and modify it.
//
// Source code generated from template: aws-my-sample-app-ios-objc v0.15
//


#import "CloudLogicAPIPathSelectorViewController.h"
#import "CloudLogicAPI.h"

@interface CloudLogicAPIPathSelectorViewController()

@property (nonatomic, strong) CloudLogicAPI *cloudLogicAPI;
@property (nonatomic, strong) NSArray<NSString *> *paths;
@property (nonatomic, strong) NSMutableArray<NSString *> *pathSuggestions;
@property (nonatomic, strong) NSString *initialText;
@property (nonatomic,weak) id <CloudLogicAPIPathSelectorModalVCDelegate> delegate;

-(void)populatePathSuggestions;

@end

@implementation CloudLogicAPIPathSelectorViewController

-(void)populatePathSuggestions {
    self.pathSuggestions = [[NSMutableArray alloc] init];
    if (self.searchText.text && self.paths) {
        for (NSString* path in self.paths) {
            if ([[path lowercaseString] containsString: [self.searchText.text lowercaseString]]) {
                [self.pathSuggestions addObject:path];
            }
        }
    }
    [self.tableView reloadData];
}

-(void)viewDidLoad {
    [super viewDidLoad];
    self.searchText.text = @"/";
    self.paths = self.cloudLogicAPI.paths;
    [self populatePathSuggestions];
}

- (IBAction)onEditingChanged:(id)sender {
    [self populatePathSuggestions];
}

- (IBAction)onSelect:(id)sender {
    [self.delegate setSelectedValue:self.searchText.text];
    [self dismissViewControllerAnimated:YES completion:nil];
}

#pragma mark - Table view data source

- (NSInteger)numberOfSectionsInTableView:(UITableView *)tableView {
    if (self.pathSuggestions) {
        return self.pathSuggestions.count;
    }
    return 0;
}

- (NSInteger)tableView:(UITableView *)tableView numberOfRowsInSection:(NSInteger)section {
    return 1;
}

- (UITableViewCell *)tableView:(UITableView *)tableView cellForRowAtIndexPath:(NSIndexPath *)indexPath {
    PathTableCell *cell = (PathTableCell *)[tableView dequeueReusableCellWithIdentifier:@"PathTableCell" forIndexPath:indexPath];
    
    NSString *path = self.pathSuggestions[indexPath.section];
    cell.path.text = path;
    return cell;
}

- (void)tableView:(UITableView *)tableView didSelectRowAtIndexPath:(NSIndexPath *)indexPath {
    [tableView deselectRowAtIndexPath:indexPath animated:YES];
    self.searchText.text = self.pathSuggestions[indexPath.section];
}

@end

@implementation PathTableCell

@end
