//
//  CloudLogicAPI.m
//  MySampleApp
//
//
// Copyright 2017 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
//
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to 
// copy, distribute and modify it.
//
// Source code generated from template: aws-my-sample-app-ios-objc v0.15
//

#import "CloudLogicAPI.h"

@interface CloudLogicAPI ()

@property (nonatomic, readwrite) NSString *displayName;
@property (nonatomic, readwrite, nullable) NSString *apiDescription;
@property (nonatomic, readwrite) NSArray<NSString *> *paths;
@property (nonatomic, readwrite) NSString *endPoint;
@property (nonatomic, readwrite) AWSAPIGatewayClient *apiClient;

@end

@implementation CloudLogicAPI

- (instancetype)initWithName:(NSString *)displayName
                       paths:(NSArray<NSString *> *)paths
                    endPoint:(NSString *)endPoint
                   apiClient:(AWSAPIGatewayClient *)apiClient
              apiDescription:(NSString * _Nullable)apiDescription{
    if (self = [super init]) {
        self.displayName = displayName;
        self.apiDescription = apiDescription;
        self.paths = paths;
        self.endPoint = endPoint;
        self.apiClient = apiClient;
    }
    return self;
}

- (instancetype)init {
    @throw [NSException exceptionWithName:NSInternalInconsistencyException
                                   reason:@"`- init` is not a valid initializer. Use `- initWithName:apiDescription:paths:endPoint:apiClient` instead."
                                 userInfo:nil];
    return nil;
}

@end
