//
//  CloudLogicAPIInvokeViewController.h
//  MySampleApp
//
//
// Copyright 2017 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
//
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to 
// copy, distribute and modify it.
//
// Source code generated from template: aws-my-sample-app-ios-objc v0.15
//

#import <UIKit/UIKit.h>

@interface CloudLogicAPIInvokeViewController : UIViewController

@property (weak, nonatomic) IBOutlet UILabel *responseTimeLabel;
@property (weak, nonatomic) IBOutlet UILabel *statusLabel;
@property (weak, nonatomic) IBOutlet UITextField *apiResponse;
@property (weak, nonatomic) IBOutlet UILabel *apiEndpoint;
@property (weak, nonatomic) IBOutlet UITextField *methodPath;
@property (weak, nonatomic) IBOutlet UILabel *methodName;
@property (weak, nonatomic) IBOutlet UITextField *queryStringParameters;
@property (weak, nonatomic) IBOutlet UITextField *requestBody;
@property (weak, nonatomic) IBOutlet UILabel *requestBodyLabel;

@end
