//
//  CloudLogicAPIOperationsViewController.m
//  MySampleApp
//
//
// Copyright 2017 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
//
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to 
// copy, distribute and modify it.
//
// Source code generated from template: aws-my-sample-app-ios-objc v0.15
//

#import "CloudLogicAPIOperationsViewController.h"
#import "CloudLogicAPI.h"
#import "CloudLogicAPIPathSelectorViewController.h"
#import "CloudLogicAPIInvokeViewController.h"

static NSArray<NSString *> *methodArray = nil;

@interface CloudLogicAPIOperationsViewController () <CloudLogicAPIPathSelectorModalVCDelegate>

@property (nonatomic, strong) CloudLogicAPI *cloudLogicAPI;
@property (nonatomic, strong) NSString *apiPathValue;

-(void)setMethodLabelText:(NSString *)text;

@end

@interface CloudLogicAPIInvokeViewController ()

@property (nonatomic, strong) CloudLogicAPI *cloudLogicAPI;
@property (nonatomic, strong) NSString *methodPathValue;
@property (nonatomic, strong) NSString *methodNameValue;
@property (nonatomic, strong) NSString *apiEndpointValue;

@end

@implementation CloudLogicAPIOperationsViewController

@synthesize delegate;

- (void)viewDidLoad {
    [super viewDidLoad];
    
    methodArray = @[@"GET", @"PUT", @"POST",
                    @"DELETE",@"PATCH", @"HEAD",
                    @"OPTIONS"];
    
    self.navigationItem.backBarButtonItem = [[UIBarButtonItem alloc] initWithTitle:@"Back"
                                                                             style:UIBarButtonItemStylePlain
                                                                            target:nil
                                                                            action:nil];
    if (self.apiPathValue) {
        self.apiPath.text = self.apiPathValue;
        [self setMethodLabelText:self.apiPathValue ];
    } else if (self.cloudLogicAPI.paths.count >= 1) {
        self.apiPath.text = self.cloudLogicAPI.paths[0];
        [self setMethodLabelText:self.cloudLogicAPI.paths[0] ];
    }
    self.apiEndpoint.text = self.cloudLogicAPI.endPoint;
}

- (void)tableView:(UITableView *)tableView didSelectRowAtIndexPath:(NSIndexPath *)indexPath {
    [tableView deselectRowAtIndexPath:indexPath animated:YES];
    static NSString *showQueryResultSeque = @"CloudLogicAPIShowInvokerSegue";
    [self performSegueWithIdentifier:showQueryResultSeque sender:[NSNumber numberWithInteger: indexPath.row]];
}

#pragma mark - Navigation

- (void)prepareForSegue:(UIStoryboardSegue *)segue sender:(id)sender {
    
    if ([segue.destinationViewController isKindOfClass:[CloudLogicAPIInvokeViewController class]]) {
        CloudLogicAPIInvokeViewController *destinationViewController = segue.destinationViewController;
        destinationViewController.cloudLogicAPI = self.cloudLogicAPI;
        destinationViewController.methodPathValue = self.apiPath.text;
        destinationViewController.methodNameValue = methodArray[[(NSNumber *)sender unsignedShortValue]];
        destinationViewController.apiEndpointValue = self.apiEndpoint.text;
    }
    
    
    if ([segue.destinationViewController isKindOfClass:[CloudLogicAPIPathSelectorViewController class]]) {
        CloudLogicAPIOperationsViewController *destinationViewController = segue.destinationViewController;
        destinationViewController.cloudLogicAPI = sender;
        destinationViewController.delegate = self;
    }
    
}

-(void)setMethodLabelText:(NSString *)text {
    self.getPathLabel.text = text;
    self.putPathLabel.text = text;
    self.postPathLabel.text = text;
    self.deletePathLabel.text = text;
    self.patchPathLabel.text = text;
    self.headPathLabel.text = text;
    self.optionPathLabel.text = text;
}

- (void)setSelectedValue:(NSString *)value {
    [self setMethodLabelText:value];
    self.apiPath.text = value;
}

- (IBAction)onBeginEditing:(id)sender {
    static NSString *showQueryResultSeque = @"PathSelectionSegue";
    [self performSegueWithIdentifier:showQueryResultSeque sender:self.cloudLogicAPI];
}

@end
