//
//  UserSettingsViewController.h
//  MySampleApp
//
//
// Copyright 2017 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
//
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to 
// copy, distribute and modify it.
//
// Source code generated from template: aws-my-sample-app-ios-objc v0.15
//
#import <UIKit/UIKit.h>

@interface UserSettingsViewController : UIViewController

- (IBAction)handlerSettings0:(id)sender;
- (IBAction)handlerSettings1:(id)sender;
- (IBAction)handlerSettings2:(id)sender;
- (IBAction)handlerSettings3:(id)sender;

@end
