//
//  AppDelegate.m
//  MySampleApp
//
//
// Copyright 2017 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
//
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to 
// copy, distribute and modify it.
//
// Source code generated from template: aws-my-sample-app-ios-objc v0.15
//
#import "AppDelegate.h"
#import <AWSCore/AWSCore.h>
#import <AWSCognito/AWSCognito.h>
#import <AWSSNS/AWSSNS.h>
#import "CloudLogicAPI.h"
#import "AWSAPI_Y4XE7A7C34_ResetBadgeCountClient.h"
#import "AWSAPI_E69N1ZSDJI_RegisterDeviceTokenClient.h"
#import "AWSConfiguration.h"
#import "AWSMobileClient.h"


#define SYSTEM_VERSION_GREATER_THAN_OR_EQUAL_TO(v)  ([[[UIDevice currentDevice] systemVersion] compare:v options:NSNumericSearch] != NSOrderedAscending)
#define SYSTEM_VERSION_LESS_THAN(v) ([[[UIDevice currentDevice] systemVersion] compare:v options:NSNumericSearch] == NSOrderedAscending)

@interface AppDelegate ()

@end

@implementation AppDelegate

- (BOOL)application:(UIApplication *)application
didFinishLaunchingWithOptions:(NSDictionary *)launchOptions {
    NSLog(@"application didFinishLaunchingWithOptions");
    
    [AWSLogger defaultLogger].logLevel = AWSLogLevelVerbose;
    
    if( SYSTEM_VERSION_LESS_THAN( @"10.0" ) )
    {
        [[UIApplication sharedApplication] registerUserNotificationSettings:[UIUserNotificationSettings settingsForTypes:(UIUserNotificationTypeSound |    UIUserNotificationTypeAlert | UIUserNotificationTypeBadge) categories:nil]];
        [[UIApplication sharedApplication] registerForRemoteNotifications];
    }
    else
    {
        UNUserNotificationCenter *center = [UNUserNotificationCenter currentNotificationCenter];
        center.delegate = self;
        [center requestAuthorizationWithOptions:(UNAuthorizationOptionSound | UNAuthorizationOptionAlert | UNAuthorizationOptionBadge) completionHandler:^(BOOL granted, NSError * _Nullable error)
         {
             if( !error )
             {
                 [[UIApplication sharedApplication] registerForRemoteNotifications];  // required to get the app to do anything at all about push notifications
                 NSLog( @"Push registration success." );
             }
             else
             {
                 NSLog( @"Push registration FAILED" );
                 NSLog( @"ERROR: %@ - %@", error.localizedFailureReason, error.localizedDescription );
                 NSLog( @"SUGGESTIONS: %@ - %@", error.localizedRecoveryOptions, error.localizedRecoverySuggestion );  
             }  
         }];  
    }
    
    UIImage *myImage = [[UIImage imageNamed:@"SermonGreenGradient.png"]
     resizableImageWithCapInsets:UIEdgeInsetsMake(0, 0, 0, 0) resizingMode:UIImageResizingModeStretch];
    
    [[UINavigationBar appearance] setBackgroundImage:myImage forBarMetrics:UIBarMetricsDefault];
    
    [[AVAudioSession sharedInstance] setCategory:AVAudioSessionCategoryPlayback error:nil];
    return [[AWSMobileClient sharedInstance] didFinishLaunching:application
                                             withOptions:launchOptions];
}

- (BOOL)application:(UIApplication *)application
            openURL:(NSURL *)url
  sourceApplication:(NSString *)sourceApplication
         annotation:(id)annotation {
    NSLog(@"application application: %@, openURL: %@, sourceApplication: %@", application.description, url.absoluteURL,
          sourceApplication);

    return [[AWSMobileClient sharedInstance] withApplication:application
                                                     withURL:url
                                       withSourceApplication:sourceApplication
                                              withAnnotation:annotation];
}

- (void)applicationWillResignActive:(UIApplication *)application {
    // Sent when the application is about to move from active to inactive state. This can occur for certain types of temporary interruptions (such as an incoming phone call or SMS message) or when the user quits the application and it begins the transition to the background state.
    // Use this method to pause ongoing tasks, disable timers, and throttle down OpenGL ES frame rates. Games should use this method to pause the game.
}

- (void)applicationDidEnterBackground:(UIApplication *)application {
    // Use this method to release shared resources, save user data, invalidate timers, and store enough application state information to restore your application to its current state in case it is terminated later.
    // If your application supports background execution, this method is called instead of applicationWillTerminate: when the user quits.
}

- (void)applicationDidBecomeActive:(UIApplication *)application {
    // Restart any tasks that were paused (or not yet started) while the application was inactive. If the application was previously in the background, optionally refresh the user interface.
    
    [UIApplication sharedApplication].applicationIconBadgeNumber = 0;
    if (self.deviceTokenInString) {
        [self resetBadgeCount:self.deviceTokenInString];
    }
}

- (void)resetBadgeCount:(NSString *)token {
    
    CloudLogicAPI *cloudLogicAPI = [[CloudLogicAPI alloc] initWithName:@"resetBadgeCount"
                                                                 paths:@[
                                                                         @"/resetBadgeCount",                                                   ]
                                                              endPoint:@"https://y4xe7a7c34.execute-api.us-west-1.amazonaws.com/beta"
                                                             apiClient: [AWSAPI_Y4XE7A7C34_ResetBadgeCountClient clientForKey:AWSCloudLogicDefaultConfigurationKey]
                                                        apiDescription:@"Resets the badge count for the device"
                                    ];
    
    
    NSDictionary *headerParameters = @{
                                       @"Content-Type": @"application/json",
                                       @"Accept": @"application/json",
                                       };
    
    NSMutableDictionary<NSString *, NSString *> *parameters = [[NSMutableDictionary alloc] init];
    NSMutableDictionary<NSString *, NSString *> *queryParameters = [[NSMutableDictionary alloc] init];
    
    
    [parameters setValue:token forKey:@"deviceToken"];
    
    
    AWSAPIGatewayRequest *apiRequest = [[AWSAPIGatewayRequest alloc] initWithHTTPMethod:@"POST"
                                                                              URLString:@"/"
                                                                        queryParameters:queryParameters
                                                                       headerParameters:headerParameters
                                                                               HTTPBody:parameters];
    
    [[cloudLogicAPI.apiClient invoke:apiRequest] continueWithBlock:^id(AWSTask *task) {
        
        if (task.error) {
            NSLog(@"Error occurred: %@", task.error);
            return task.error;
        }
        
        AWSAPIGatewayResponse *response = (AWSAPIGatewayResponse *)task.result;
        NSString *responseString = [[NSString alloc] initWithData:response.responseData encoding:NSUTF8StringEncoding];
        NSString *statusCode = [NSString stringWithFormat: @"%ld", (long)response.statusCode];
        NSLog(@"Response: %@", responseString);
        NSLog(@"Status Code: %@", statusCode);
        
        return nil;
    }];
}

- (void)applicationWillTerminate:(UIApplication *)application {
    // Called when the application is about to terminate. Save data if appropriate. See also applicationDidEnterBackground:.
}

-(NSString*)deviceTokenAsString:(NSData*)deviceTokenData
{
    NSString *rawDeviceTring = [NSString stringWithFormat:@"%@", deviceTokenData];
    NSString *noSpaces = [rawDeviceTring stringByReplacingOccurrencesOfString:@" " withString:@""];
    NSString *tmp1 = [noSpaces stringByReplacingOccurrencesOfString:@"<" withString:@""];
    
    return [tmp1 stringByReplacingOccurrencesOfString:@">" withString:@""];
}

- (void)registerDeviceToken:(NSString *)token {
    CloudLogicAPI *cloudLogicAPI = [[CloudLogicAPI alloc] initWithName:@"registerDeviceToken"
                                                                 paths:@[
                                                                         @"/registerDeviceToken",                                                   ]
                                                              endPoint:@"https://e69n1zsdji.execute-api.us-west-1.amazonaws.com/beta"
                                                             apiClient: [AWSAPI_E69N1ZSDJI_RegisterDeviceTokenClient clientForKey:AWSCloudLogicDefaultConfigurationKey]
                                                        apiDescription:@"Registers devices tokens and generates endpointArne"
                                    ];
    
    
    NSDictionary *headerParameters = @{
                                       @"Content-Type": @"application/json",
                                       @"Accept": @"application/json",
                                       };
    
    NSMutableDictionary<NSString *, NSString *> *parameters = [[NSMutableDictionary alloc] init];
    NSMutableDictionary<NSString *, NSString *> *queryParameters = [[NSMutableDictionary alloc] init];
    
    
    [parameters setValue:token forKey:@"deviceToken"];
    [parameters setValue:@"ios" forKey:@"platform"];
    
    
    AWSAPIGatewayRequest *apiRequest = [[AWSAPIGatewayRequest alloc] initWithHTTPMethod:@"POST"
                                                                              URLString:@"/"
                                                                        queryParameters:queryParameters
                                                                       headerParameters:headerParameters
                                                                               HTTPBody:parameters];
    
    [[cloudLogicAPI.apiClient invoke:apiRequest] continueWithBlock:^id(AWSTask *task) {
        
        if (task.error) {
            NSLog(@"Error occurred: %@", task.error);
            return task.error;
        }
        
        AWSAPIGatewayResponse *response = (AWSAPIGatewayResponse *)task.result;
        NSString *responseString = [[NSString alloc] initWithData:response.responseData encoding:NSUTF8StringEncoding];
        NSString *statusCode = [NSString stringWithFormat: @"%ld", (long)response.statusCode];
        NSLog(@"Response: %@", responseString);
        NSLog(@"Status Code: %@", statusCode);
        
        return nil;
    }];

}

- (void)application:(UIApplication *)application didRegisterForRemoteNotificationsWithDeviceToken:(NSData *)deviceToken {
    [[AWSMobileClient sharedInstance] application:application
 didRegisterForRemoteNotificationsWithDeviceToken:deviceToken];
    
    self.deviceTokenInString = [self deviceTokenAsString:deviceToken];
    NSLog(@"Device Token is : %@", self.deviceTokenInString);
    [self resetBadgeCount:self.deviceTokenInString];
    [self registerDeviceToken:self.deviceTokenInString];
}

- (void)application:(UIApplication *)application didFailToRegisterForRemoteNotificationsWithError:(NSError *)error {
    [[AWSMobileClient sharedInstance] application:application
 didFailToRegisterForRemoteNotificationsWithError:error];
}

- (void)application:(UIApplication *)application didReceiveRemoteNotification:(NSDictionary *)userInfo {
    [[UIApplication sharedApplication] setApplicationIconBadgeNumber:[UIApplication sharedApplication].applicationIconBadgeNumber+1];
}

- (void) application:(UIApplication *)application
didReceiveRemoteNotification:(NSDictionary *)userInfo
fetchCompletionHandler:(void (^)(UIBackgroundFetchResult))completionHandler {
    [[AWSMobileClient sharedInstance] application:application
                     didReceiveRemoteNotification:userInfo
                           fetchCompletionHandler:completionHandler];
    completionHandler(UIBackgroundFetchResultNewData);
    [[UIApplication sharedApplication] setApplicationIconBadgeNumber:[UIApplication sharedApplication].applicationIconBadgeNumber+1];
}

- (void)userNotificationCenter:(UNUserNotificationCenter *)center
       willPresentNotification:(UNNotification *)notification
         withCompletionHandler:(void (^)(UNNotificationPresentationOptions options))completionHandler
{
    NSLog( @"Handle push from foreground" );
    // custom code to handle push while app is in the foreground
    NSLog(@"%@", notification.request.content.userInfo);
}

- (void)userNotificationCenter:(UNUserNotificationCenter *)center
didReceiveNotificationResponse:(UNNotificationResponse *)response
         withCompletionHandler:(void (^)())completionHandler
{
    NSLog( @"Handle push from background or closed" );
    // if you set a member variable in didReceiveRemoteNotification, you  will know if this is from closed or background
    NSLog(@"%@", response.notification.request.content.userInfo);
}

@end
