//
//  AWSUserFilesViewController.h
//  MySampleApp
//
//
// Copyright 2017 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
//
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to 
// copy, distribute and modify it.
//
// Source code generated from template: aws-my-sample-app-ios-objc v0.15
//
#import <UIKit/UIKit.h>

@class AWSContent;
@class AWSLocalContent;

@interface UserFilesViewController : UITableViewController

@property (weak, nonatomic) IBOutlet UILabel *cacheLimitLabel;
@property (weak, nonatomic) IBOutlet UILabel *currentCacheSizeLabel;
@property (weak, nonatomic) IBOutlet UILabel *availableCacheSizeLabel;
@property (weak, nonatomic) IBOutlet UILabel *pinnedCacheSizeLabel;
@property (weak, nonatomic) IBOutlet UILabel *pathLabel;
@property (weak, nonatomic) IBOutlet UISegmentedControl *segmentedControl;

@property (strong, nonatomic) NSString *prefix;
@property (nonatomic) NSInteger segmentedIndex;

- (IBAction)changeDirectory:(UISegmentedControl *)sender;

@end

@interface UserFilesCell : UITableViewCell

@property (weak, nonatomic) IBOutlet UILabel *fileNameLabel;
@property (weak, nonatomic) IBOutlet UILabel *detailLabel;
@property (weak, nonatomic) IBOutlet UIImageView *keepImageView;
@property (weak, nonatomic) IBOutlet UIImageView *downloadedImageView;
@property (weak, nonatomic) IBOutlet UIProgressView *progressView;

@property (strong, nonatomic) AWSContent *content;
@property (strong, nonatomic) NSString *prefix;

@end

@interface UserFilesImageViewController : UIViewController

@property (weak, nonatomic) IBOutlet UIImageView *imageView;
@property (strong, nonatomic) UIImage *image;

@end

@interface UserFilesUploadCell : UITableViewCell

@property (weak, nonatomic) IBOutlet UILabel *fileNameLabel;
@property (weak, nonatomic) IBOutlet UIProgressView *progressView;

@property (strong, nonatomic) AWSLocalContent *localContent;
@property (strong, nonatomic) NSString *prefix;

@end
