//
//  AWSConfiguration.m
//  MySampleApp
//
//
// Copyright 2017 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
//
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to 
// copy, distribute and modify it.
//
// Source code generated from template: aws-my-sample-app-ios-objc v0.16
//
//

#import "AWSConfiguration.h"
// This ServiceKey variable is used to determine which configuration to use.
// If it is a release build, it will use the Prod platform configuration.
// If it's not (debug build), it will default to the Devo (Sandbox) platform configuration.

#if RELEASE
NSString *const ServiceKey = @"Prod";
#else
NSString *const ServiceKey = @"Prod";
#endif




// Cognito User Pools Identity Id
NSString *const AWSCognitoUserPoolId = @"us-west-2_SDOpd56WN";

// Cognito User Pools App Client Id
NSString *const AWSCognitoUserPoolClientId = @"4uvof73eivpevcsbdr4avbscn6";

// Cognito User Pools Client Secret
NSString *const AWSCognitoUserPoolClientSecret = @"1k2pfq9ce8dmpj3pf1b70fqih810dbtq9aqncc36absq0gps9k42";

// Cognito User Pools Region
AWSRegionType const AWSCognitoUserPoolRegion = AWSRegionUSWest2;

// Identifier for Cloud Logic API invocation clients
NSString *const AWSCloudLogicDefaultConfigurationKey = @"CloudLogicAPIKey";
AWSRegionType const AWSCloudLogicDefaultRegion = AWSRegionUSWest1;
