//
//  Announcements.m
//  MySampleApp
//
//
// Copyright 2017 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
//
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to 
// copy, distribute and modify it.
//
// Source code generated from template: aws-my-sample-app-ios-objc v0.16
//


#import "Announcements.h"
#import "NoSQLSampleDataGenerator.h"
#import <AWSMobileHubHelper/AWSMobileHubHelper.h>
#import <sys/utsname.h>


@implementation Announcements

+ (NSString *)dynamoDBTableName {

    return @"joyfulchurch-mobilehub-687604833-Announcements";
}

+ (NSString *)hashKeyAttribute {

    return @"_userId";
}

+ (NSString *)rangeKeyAttribute {

    return @"_creationDate";
}

+ (NSDictionary *)JSONKeyPathsByPropertyKey {
    return @{
               @"_userId" : @"userId",
               @"_creationDate" : @"creationDate",
               @"_announcementId" : @"announcementId",
               @"_category" : @"category",
               @"_content" : @"content",
               @"_keywords" : @"keywords",
               @"_title" : @"title",
             };
}

@end
