//
//  NotificationChannels.m
//  MySampleApp
//
//
// Copyright 2017 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
//
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to 
// copy, distribute and modify it.
//
// Source code generated from template: aws-my-sample-app-ios-objc v0.19
//


#import "NotificationChannels.h"
#import "NoSQLSampleDataGenerator.h"
#import <AWSMobileHubHelper/AWSMobileHubHelper.h>
#import <sys/utsname.h>


@implementation NotificationChannels

+ (NSString *)dynamoDBTableName {

    return @"joyfulchurch-mobilehub-687604833-NotificationChannels";
}

+ (NSString *)hashKeyAttribute {

    return @"_deviceToken";
}

+ (NSString *)rangeKeyAttribute {

    return @"_channel";
}

+ (NSDictionary *)JSONKeyPathsByPropertyKey {
    return @{
               @"_deviceToken" : @"deviceToken",
               @"_channel" : @"channel",
             };
}

@end
