//
//  NotificationChannels.h
//  MySampleApp
//
//
// Copyright 2017 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
//
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to 
// copy, distribute and modify it.
//
// Source code generated from template: aws-my-sample-app-ios-objc v0.19
//

@import UIKit;
@import AWSDynamoDB;

#import "NoSQLModelHelpers.h"

NS_ASSUME_NONNULL_BEGIN


@interface NotificationChannels : AWSDynamoDBObjectModel <AWSDynamoDBModeling>

+ (NSDictionary *)JSONKeyPathsByPropertyKey;

@property (nonatomic, strong) NSString *_deviceToken;
@property (nonatomic, strong) NSString *_channel;

@end

NS_ASSUME_NONNULL_END
