//
//  Sermons.m
//  MySampleApp
//
//
// Copyright 2017 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
//
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to 
// copy, distribute and modify it.
//
// Source code generated from template: aws-my-sample-app-ios-objc v0.16
//


#import "Sermons.h"
#import "NoSQLSampleDataGenerator.h"
#import <AWSMobileHubHelper/AWSMobileHubHelper.h>
#import <sys/utsname.h>


@implementation Sermons

+ (NSString *)dynamoDBTableName {

    return @"joyfulchurch-mobilehub-687604833-Sermons";
}

+ (NSString *)hashKeyAttribute {

    return @"_userId";
}

+ (NSString *)rangeKeyAttribute {

    return @"_creationDate";
}

+ (NSDictionary *)JSONKeyPathsByPropertyKey {
    return @{
               @"_userId" : @"userId",
               @"_creationDate" : @"creationDate",
               @"_keywords" : @"keywords",
               @"_series" : @"series",
               @"_sermon" : @"sermon",
               @"_sermonId" : @"sermonId",
               @"_title" : @"title",
               @"_verse" : @"verse",
             };
}

@end
