//
//  UserDataStorageViewController.m
//  MySampleApp
//
//
// Copyright 2017 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
//
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to 
// copy, distribute and modify it.
//
// Source code generated from template: aws-my-sample-app-ios-objc v0.15
//
#import "UserDataStorageViewController.h"

@interface UserDataStorageViewController ()

@end

@implementation UserDataStorageViewController

- (void)viewDidLoad {
    [super viewDidLoad];

    self.navigationItem.backBarButtonItem = [[UIBarButtonItem alloc] initWithTitle:@"Back"
                                                                             style:UIBarButtonItemStylePlain
                                                                            target:nil
                                                                            action:nil];
    self.featureTextView.contentInset = UIEdgeInsetsMake(-4, -4, -4, -4);
}

- (void)viewDidAppear:(BOOL)animated {
    [super viewDidAppear:animated];

    [self.featureTextView flashScrollIndicators];
}

- (IBAction)demoUserFileStorage:(UIButton *)sender {
    UIStoryboard *storyboard = [UIStoryboard storyboardWithName:@"UserFiles"
                                                         bundle:nil];
    UIViewController *viewController = [storyboard instantiateViewControllerWithIdentifier:@"UserFiles"];

    [self.navigationController pushViewController:viewController
                                         animated:YES];
}

- (IBAction)demoUserSettings:(UIButton *)sender {
    UIStoryboard *storyboard = [UIStoryboard storyboardWithName:@"UserSettings"
                                                         bundle:nil];
    UIViewController *viewController = [storyboard instantiateViewControllerWithIdentifier:@"UserSettings"];

    [self.navigationController pushViewController:viewController
                                         animated:YES];
}

@end
