//
//  AnnouncementsTable.h
//  MySampleApp
//
//
// Copyright 2017 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
//
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to 
// copy, distribute and modify it.
//
// Source code generated from template: aws-my-sample-app-ios-objc v0.15
//

@import UIKit;
@import AWSDynamoDB;

#import "NoSQLModelHelpers.h"

NS_ASSUME_NONNULL_BEGIN


@interface AnnouncementsTable : Table

@end


@interface AnnouncementsPrimaryIndex: Index

@end


@interface AnnouncementsCategories: Index

@end


NS_ASSUME_NONNULL_END
