//
//  NoSQLTableListViewControllers.h
//  MySampleApp
//
//
// Copyright 2017 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
//
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to 
// copy, distribute and modify it.
//
// Source code generated from template: aws-my-sample-app-ios-objc v0.15
//
#import <UIKit/UIKit.h>

@interface NoSQLTableListViewController : UITableViewController

@end

@interface NoSQLTableListCell : UITableViewCell

@property (weak, nonatomic) IBOutlet UILabel *tableNameLabel;
@property (weak, nonatomic) IBOutlet UILabel *partitionKeyLabel;
@property (weak, nonatomic) IBOutlet UILabel *sortKeyLabel;
@property (weak, nonatomic) IBOutlet UILabel *numberOfIndexesLabel;

@end
