//
//  NoSQLQueryResultViewController.h
//  MySampleApp
//
//
// Copyright 2017 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
//
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to 
// copy, distribute and modify it.
//
// Source code generated from template: aws-my-sample-app-ios-objc v0.15
//
#import <UIKit/UIKit.h>
@import AWSDynamoDB;

@class Table;

@interface NoSQLQueryResultViewController : UITableViewController

@property (weak, nonatomic) IBOutlet UILabel *queryDescriptionLabel;

@property (nonatomic, strong) NSString *queryType;
@property (nonatomic, strong) NSString *queryDescription;
@property (nonatomic, strong) Table *table;
@property (nonatomic, strong) NSArray<AWSDynamoDBObjectModel<AWSDynamoDBModeling> *> *results;
@property (nonatomic, strong) AWSDynamoDBPaginatedOutput *paginatedOutput;

@end

@interface NoSQLQueryResultCell : UITableViewCell

@property (weak, nonatomic) IBOutlet UILabel *attributeNameLabel;
@property (weak, nonatomic) IBOutlet UILabel *attributeValueLabel;

@end
