//
//  NoSQLTableViewController.h
//  MySampleApp
//
//
// Copyright 2017 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
//
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to 
// copy, distribute and modify it.
//
// Source code generated from template: aws-my-sample-app-ios-objc v0.15
//
#import <UIKit/UIKit.h>

@class Table;

@interface NoSQLTableViewController : UITableViewController

@property (nonatomic, strong) Table *table;
@property (strong, nonatomic) IBOutlet UIActivityIndicatorView *activityIndicator;

- (IBAction)insertSampleData:(id)sender;

- (IBAction)confirmSampleDataRemoval:(id)sender;

@end

@interface NoSQLTableCell : UITableViewCell

@property (weak, nonatomic) IBOutlet UILabel *queryTypeLabel;
@property (weak, nonatomic) IBOutlet UILabel *queryDescriptionLabel;

@property (nonatomic, strong) NSString *queryType;

@end
