//
//  NoSQLTableFactory.m
//  MySampleApp
//
//
// Copyright 2017 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
//
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to 
// copy, distribute and modify it.
//
// Source code generated from template: aws-my-sample-app-ios-objc v0.15
// 
#import "NoSQLTableFactory.h"


#import "SermonsTable.h"

#import "AnnouncementsTable.h"

@implementation NoSQLTableFactory

+ (NSArray<Table *> *)supportedTables {
    return @[

             [SermonsTable new],

             [AnnouncementsTable new],
             ];
}

@end
