//
//  NoSQLTableListViewController.m
//  MySampleApp
//
//
// Copyright 2017 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
//
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to 
// copy, distribute and modify it.
//
// Source code generated from template: aws-my-sample-app-ios-objc v0.15
//
#import "NoSQLTableListViewController.h"
#import "NoSQLTableFactory.h"
#import "NoSQLModelHelpers.h"
#import "NoSQLTableViewController.h"

@interface NoSQLTableListViewController ()

@property (nonatomic, strong) NSArray<Table *> *tables;

@end

@implementation NoSQLTableListViewController

- (void)viewDidLoad {
    [super viewDidLoad];

    self.navigationItem.backBarButtonItem = [[UIBarButtonItem alloc] initWithTitle:@"Back"
                                                                             style:UIBarButtonItemStylePlain
                                                                            target:nil
                                                                            action:nil];

    self.tables = [NoSQLTableFactory supportedTables];
}

#pragma mark - Table view data source

- (NSInteger)numberOfSectionsInTableView:(UITableView *)tableView {
    return [self.tables count];
}

- (NSInteger)tableView:(UITableView *)tableView numberOfRowsInSection:(NSInteger)section {
    return 1;
}

- (UITableViewCell *)tableView:(UITableView *)tableView cellForRowAtIndexPath:(NSIndexPath *)indexPath {
    NoSQLTableListCell *cell = [tableView dequeueReusableCellWithIdentifier:@"NoSQLTableListCell" forIndexPath:indexPath];

    Table *table = self.tables[indexPath.section];
    cell.tableNameLabel.text = table.tableDisplayName;
    
    cell.partitionKeyLabel.text = [NSString stringWithFormat: @"%@ (%@)", [table tableAttributeName:table.partitionKeyName], table.partitionKeyType];
    cell.sortKeyLabel.text = @"-";
    if (table.sortKeyName) {
        cell.sortKeyLabel.text = [NSString stringWithFormat: @"%@ (%@)", [table tableAttributeName:table.sortKeyName], table.sortKeyType];
    }
    cell.numberOfIndexesLabel.text = [@([table.indexes count]) stringValue];

    return cell;
}

- (void)tableView:(UITableView *)tableView didSelectRowAtIndexPath:(NSIndexPath *)indexPath {
    [tableView deselectRowAtIndexPath:indexPath animated:YES];

    static NSString *showQueryResultSeque = @"NoSQLShowTableDetailsSegue";
    [self performSegueWithIdentifier:showQueryResultSeque sender:self.tables[indexPath.section]];
}

#pragma mark - Navigation

- (void)prepareForSegue:(UIStoryboardSegue *)segue sender:(id)sender {
    if ([segue.destinationViewController isKindOfClass:[NoSQLTableViewController class]]) {
        NoSQLTableViewController *destinationViewController = segue.destinationViewController;
        destinationViewController.table = sender;
    }
}

@end

@implementation NoSQLTableListCell

@end
